In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
import pickle

In [2]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [3]:
data=data.drop(["RowNumber","CustomerId","Surname"],axis=1)
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [4]:
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [6]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [7]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [8]:
geo_encoded_df=pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [9]:
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 13 columns]

In [11]:
with open('label_encoder_gender.pkl','wb')as file:
    pickle.dump(label_encoder_gender,file)
with open('onehot_encoder_geo.pkl','wb')as file:
    pickle.dump(onehot_encoder_geo,file)

In [ ]:
X=data.drop('Exited',axis=1)
y=data['Exited']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [13]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [1]:
with open('scaler.pkl','wb')as file:
    pickle.dump(scaler,file)

NameError: name 'pickle' is not defined

In [16]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [17]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid')
])

WARNING:tensorflow:From c:\Users\divya\OneDrive\Desktop\ANN Classification\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [19]:
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

WARNING:tensorflow:From c:\Users\divya\OneDrive\Desktop\ANN Classification\venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [20]:
log_dir="logs/fit"+datetime.datetime.now().strftime("%Y-%m-%d-%H-%M-%S")
Tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [22]:
early_stopping_callback=EarlyStopping(monitor="val_loss",patience=10,restore_best_weights=True)

In [23]:
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[Tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\divya\OneDrive\Desktop\ANN Classification\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\divya\OneDrive\Desktop\ANN Classification\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 7s 10ms/step - loss: 0.4449 - accuracy: 0.8116 - val_loss: 0.3895 - val_accuracy: 0.8310
Epoch 2/100
250/250 [==============================] - 4s 17ms/step - loss: 0.3815 - accuracy: 0.8422 - val_loss: 0.3557 - val_accuracy: 0.8525
Epoch 3/100
250/250 [==============================] - 7s 28ms/step - loss: 0.3539 - accuracy: 0.8547 - val_loss: 0.3524 - val_accuracy: 0.8570
Epoch 4/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3443 - accuracy: 0.8601 - val_loss: 0.3488 - val_accuracy: 0.8600
Epoch 5/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3388 - accuracy: 0.8640 - val_loss: 0.3424 - val_accuracy: 0.8615
Epoch 6/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3358 - accuracy: 0.8605 - val_loss: 0.3425 - val_accuracy: 0.8575
Epoch 7/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3320 - accuracy: 0.8622 - val_loss: 0.3404 - val_accuracy: 0.8590
Epoch 8/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3292 - accuracy: 0.8641 - val_loss: 0.3384 - val_accuracy: 0.8645
Epoch 9/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3263 - accuracy: 0.8648 - val_loss: 0.3451 - val_accuracy: 0.8575
Epoch 10/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3263 - accuracy: 0.8658 - val_loss: 0.3392 - val_accuracy: 0.8615
Epoch 11/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3239 - accuracy: 0.8687 - val_loss: 0.3407 - val_accuracy: 0.8595
Epoch 12/100
250/250 [==============================] - 3s 10ms/step - loss: 0.3218 - accuracy: 0.8665 - val_loss: 0.3441 - val_accuracy: 0.8600
Epoch 13/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3215 - accuracy: 0.8662 - val_loss: 0.3414 - val_accuracy: 0.8605
Epoch 14/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3206 - accuracy: 0.8692 - val_loss: 0.3386 - val_accuracy: 0.8655
Epoch 15/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3177 - accuracy: 0.8692 - val_loss: 0.3377 - val_accuracy: 0.8640
Epoch 16/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3171 - accuracy: 0.8687 - val_loss: 0.3372 - val_accuracy: 0.8630
Epoch 17/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3144 - accuracy: 0.8705 - val_loss: 0.3380 - val_accuracy: 0.8610
Epoch 18/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3148 - accuracy: 0.8709 - val_loss: 0.3415 - val_accuracy: 0.8605
Epoch 19/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3122 - accuracy: 0.8724 - val_loss: 0.3470 - val_accuracy: 0.8605
Epoch 20/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3116 - accuracy: 0.8683 - val_loss: 0.3387 - val_accuracy: 0.8610
Epoch 21/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3114 - accuracy: 0.8700 - val_loss: 0.3462 - val_accuracy: 0.8580
Epoch 22/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3115 - accuracy: 0.8690 - val_loss: 0.3424 - val_accuracy: 0.8660
Epoch 23/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3094 - accuracy: 0.8692 - val_loss: 0.3402 - val_accuracy: 0.8645
Epoch 24/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3076 - accuracy: 0.8717 - val_loss: 0.3397 - val_accuracy: 0.8635
Epoch 25/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3073 - accuracy: 0.8729 - val_loss: 0.3462 - val_accuracy: 0.8580
Epoch 26/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3057 - accuracy: 0.8740 - val_loss: 0.3441 - val_accuracy: 0.8585

In [24]:
model.save('model.h5')

c:\Users\divya\OneDrive\Desktop\ANN Classification\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [25]:
%load_ext tensorboard

In [27]:
%tensorboard --logdir logs/fit2026-03-11-11-50-43